### ISSUE TITLE
Verify cert pinning is working

### ISSUE THREAD

**Issue by xzinkus** [WhiteHatCP/seclab-bot#14]
I'm like _somewhat_ sure it works.

**Comment by slashnick** [comment]
We can pin our public key because whenever we renew our cert, the new cert uses the same public key.  I'm pretty sure the bot isn't doing that right now.

**Comment by xzinkus** [comment]
This should be added, I think the existing code has traces of making this happen, or at least the git history does. Then, it should be tested with an attempted mitm :)
