### ISSUE TITLE
Use TLS 1.3 and update the cipher suite specification

### ISSUE THREAD

**Issue by xzinkus** [WhiteHatCP/seclab-bot#15]
`SSL_CIPHER_LIST` should be set to only the best ciphers in TLS 1.3.

Additionally, the `ssl socket` is a TLS 1.2 connection. It should be 1.3 ASAP.

**Comment by slashnick** [comment]
Make sure nginx on the server is accepting TLS 1.3 before pushing. We may need to upgrade.
