### ISSUE TITLE
MitM/Replay Security

### ISSUE THREAD

**Issue by slashnick** [WhiteHatCP/seclab-bot#3]
Here's an attack vector - I watch all the (unencrypted) message traffic until I see one close message and one open message.  Each of these messages include a valid hmac.  So if the server isn't validating timestamps, I can replay either of these two messages and control the open status without ever knowing the key.

Note that expiring messages by age won't always solve this issue.  Suppose I close the lab by accident, then realize my mistake and open it again.  If the second message is sent before the first message expires, an attacker could replay the "close" message and override the "open" message.

**Comment by xzinkus** [comment]
Yep, that's why I had TLS in there. I'm currently reviewing the merits of using python ssl linked to OpenSSL vs. building our own based on LibreSSL

**Comment by slashnick** [comment]
TLS would solve everything apart from a MITM selectively blocking connections inferred to be "open" messages (by time of day or whatever), but this is somewhat mitigated by #4.

**Comment by xzinkus** [comment]
Nope, pin the cert in the client and MitM is impossible

**Comment by slashnick** [comment]
MitM was a loose term, more like "pass through all TCP traffic... unless it I think it's going to be an open connection, then block the whole thing"

**Comment by xzinkus** [comment]
We can't do anything about an attacker dropping all of our traffic. The error message saying 'We didn't get an "all-good" from the server' is all we can do for that attack.

**Comment by slashnick** [comment]
Yep.  The connection error would get reported to the user, so the attack wouldn't succeed silently.

**Comment by xzinkus** [comment]
Sounds good! :+1:
