### ISSUE TITLE
Server Response

### ISSUE THREAD

**Issue by slashnick** [WhiteHatCP/seclab-bot#4]
It would be useful to have some sort of indicator on the bot (e.g. LED on an Arduino) that confirms the lab status has been changed successfully.  This will verify that the bot is on, button press was registered, the server was up and reachable, the HMAC was accepted, and the actual status indicator (e.g. a badge on the homepage) was properly updated.

If we want to implement this, some sort of response message would need to be specified, potentially HMAC signed (so an attacker can't MITM you, block all your "open" messages, and respond to them saying they were successful so no one notices).

An example might be to respond with the same 5-byte message, followed by some kind of status byte (0xFF for "all good", 0x00 for errors such as a bad hash, problem updating status, etc.).

Another possibility would be either an "all good" message as a response, and simply closing the connection when there's an error of any kind.

**Comment by xzinkus** [comment]
Yep, I'll add an "All good" similarly HMAC'd and a disconnect on error.
