### ISSUE TITLE
4-byte timestamp might not be optimal

### ISSUE THREAD

**Issue by slashnick** [WhiteHatCP/seclab-bot#6]
Using 32 bits for our timestamp may break our code a couple decades from now, if not properly planned for.

See: [Year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem).

**Comment by xzinkus** [comment]
Yes! good call, let's go for eight and hope the world doesn't last too long :)

**Comment by xzinkus** [comment]
(noting that the Pi, and TLS1.2 will both give out long before then, but who cares, it's a few extra bytes)

**Comment by slashnick** [comment]
Let's hope someone remembers to update this system in a couple hundred billion years.

**Comment by xzinkus** [comment]
Hehe TLS1.2 won't last near that long
